# Generated by Django 3.1.5 on 2021-01-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0002_article_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created_at']},
        ),
    ]
